### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by punkpeye** [sirmews/mcp-pinecone#3]
I'm trying to start this server so I can mark the associated [listing](https://glama.ai/mcp/servers/fuooftj328) as tested.

### Current Behavior

This is my `Dockerfile`:

```Dockerfile
FROM python:3.12

RUN pip install uv

WORKDIR /app

RUN git clone https://github.com/sirmews/mcp-pinecone .



RUN uv sync

CMD ["uv", "run", "mcp-pinecone"]
```

When I run it, I get the following error:

```
Traceback (most recent call last):
  File "/app/.venv/bin/mcp-pinecone", line 5, in <module>
    from mcp_pinecone import main
  File "/app/src/mcp_pinecone/__init__.py", line 1, in <module>
    from . import server
  File "/app/src/mcp_pinecone/server.py", line 8, in <module>
    from .pinecone import PineconeClient, PineconeRecord
  File "/app/src/mcp_pinecone/pinecone.py", line 5, in <module>
    from .constants import (
  File "/app/src/mcp_pinecone/constants.py", line 42, in <module>
    PINECONE_INDEX_NAME, PINECONE_API_KEY = get_pinecone_config()
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/mcp_pinecone/constants.py", line 34, in get_pinecone_config
    raise ValueError(
ValueError: Pinecone API key is required. Provide it via --api-key argument or PINECONE_API_KEY environment variable

```

### Expected Behavior

The server should start correctly when using `uv run`.

### Suggested Improvement

I believe the issue here is that README does not mention `PINECONE_API_KEY` as a requirement.

Could you provide a complete example in the README showing how to start the server using uv run?

This would improve usability for developers and help automated systems like [Glama](https://glama.ai/mcp/servers) to test the server

**Comment by sirmews** [comment]
@punkpeye Thanks for pointing out Glama. I'll have a look. I've updated the README and specifically mentioned PINECONE_API_KEY and
